name: Build

on:
  push:
    branches: ['*']
    tags-ignore: ['*']
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDk
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - name: Build
        run: gradle build
      - name: Publish SNAPSHOT
        if: ${{ github.ref_name == 'dev' }}
        run: gradle publishToSonatype